#!/bin/sh
set -eu

# Regenerates the OpenCC data shipped as Flutter assets (assets/opencc).
#
# OpenCC's source configs reference compiled .ocd2 dictionaries, so the text
# configs and a handful of dictionaries are generated by its CMake build. This
# script builds them for the pinned submodule and copies the result into
# assets/opencc, which is committed so `flutter build` needs no extra step.
#
# Usage: tool/sync_opencc_assets.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_DIR="$ROOT_DIR/build/opencc/out/share/opencc"
DEST_DIR="$ROOT_DIR/assets/opencc"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

require_command cp

OPENCC_DICT_FORMAT=text "$ROOT_DIR/tool/build_opencc.sh"

if [ ! -d "$SOURCE_DIR" ]; then
  echo "error: $SOURCE_DIR is missing after building OpenCC" >&2
  exit 1
fi

mkdir -p "$DEST_DIR"
for file in "$SOURCE_DIR"/*.json "$SOURCE_DIR"/*.txt; do
  [ -e "$file" ] || continue
  cp "$file" "$DEST_DIR/"
done

# Keep the license, attribution and pinned version next to the data: they are
# shown on the app's license page and the version names the extraction
# directory used at runtime. Four of the generated dictionaries have their
# upstream comment headers stripped by OpenCC's generator, hence the explicit
# NOTICE describing where the data comes from.
VERSION="$(git -C "$ROOT_DIR/third_party/opencc" describe --tags)"
cp "$ROOT_DIR/third_party/opencc/LICENSE" "$DEST_DIR/LICENSE"
cp "$ROOT_DIR/third_party/opencc/AUTHORS" "$DEST_DIR/AUTHORS"
printf '%s\n' "$VERSION" > "$DEST_DIR/version.txt"

cat > "$DEST_DIR/NOTICE" <<NOTICE
Open Chinese Convert (OpenCC)
https://github.com/BYVoid/OpenCC

Copyright Carbo Kuo and OpenCC contributors (see AUTHORS).
Licensed under the Apache License, Version 2.0 (see LICENSE).

This app bundles data generated by OpenCC's own CMake build ($VERSION): the
JSON conversion configs in this directory and the plain-text dictionaries they
reference. The data is unmodified upstream data; the build only switched the
dictionaries and configs to OpenCC's "text" format. The bundled libopencc
shared library is compiled from the same pinned source.
NOTICE

echo "Synced OpenCC $(cat "$DEST_DIR/version.txt") assets into assets/opencc"
