repo_url: https://kobe-koto.github.io/FluentLyrics/fdroid/repo
repo_name: FluentLyrics
repo_icon: icon.png
repo_description: >-
  Official custom F-Droid repository for FluentLyrics Android releases.
